services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pg_db

  pg_db:
    image: postgres:16.8-alpine3.21
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
  my_media:
