# Generated by Django 5.1.7 on 2025-03-14 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("station", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journeymodel",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="station.routemodel",
            ),
        ),
        migrations.AddField(
            model_name="routemodel",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routers_to",
                to="station.stationmodel",
            ),
        ),
        migrations.AddField(
            model_name="routemodel",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routers_from",
                to="station.stationmodel",
            ),
        ),
        migrations.AddField(
            model_name="ticketmodel",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.journeymodel",
            ),
        ),
        migrations.AddField(
            model_name="ticketmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.ordermodel",
            ),
        ),
        migrations.AddField(
            model_name="journeymodel",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="station.trainmodel",
            ),
        ),
        migrations.AddField(
            model_name="trainmodel",
            name="train_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="station.traintypemodel",
                verbose_name="trains",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainmodel",
            constraint=models.UniqueConstraint(
                fields=("cargo_num", "places_in_cargo"),
                name="unique_cargo_num_places_in_cargo",
            ),
        ),
    ]
