# Generated by Django 5.1.7 on 2025-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trainmodel",
            name="unique_cargo_num_places_in_cargo",
        ),
        migrations.AddConstraint(
            model_name="ticketmodel",
            constraint=models.UniqueConstraint(
                fields=("cargo", "seat"), name="unique_cargo_seat"
            ),
        ),
    ]
