# Generated by Django 5.1.7 on 2025-03-16 10:22

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "station",
            "0003_remove_trainmodel_unique_cargo_num_places_in_cargo_and_more"
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stationmodel",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.station_image_path
            ),
        ),
        migrations.AddField(
            model_name="trainmodel",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.train_image_path
            ),
        ),
    ]
